{% set name = "pandas-vet" %}
{% set version = "2023.8.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: ae9fd528d5d41c33ff101afb775fc19e619b0bcf6785c7dea86b6e0087879920

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - attrs
    - flake8 >3.0.0
    - python >=3.6
    - setuptools

test:
  imports:
    - pandas_vet

about:
  home: https://github.com/deppen8/pandas-vet
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A flake8 plugin to lint pandas in an opinionated way
  dev_url: https://github.com/deppen8/pandas-vet

extra:
  recipe-maintainers:
    - deppen8
