travis:
  secure:
    BINSTAR_TOKEN: RHCql90xOrWk7oMT1Xl+ENhwuAnvpKDPvdpKn8te0hsFyFeq5CjRZ2Ty2h9Rvq9tU8FMccBwiIisLDjuGusr4Hm0jrCE0jKqqbJv3p7vLkaf7T61FBZv1q7K2VuMwXcA3QKqgLUb4i1jenDR8ftdjbBF6uGvNBVdoG8rYsdBCVyXHTMuyFJXJ8jlWlTt30zGXbmlC+lndUJLKoJrnbDO7GUKD+DVCQOGwIZMIkefwxA9HkgbgcbP7m1eEmtNlwvrn/mX6InHZIbxQt/iwva8BgEivSboglSr7MOa85UQ23CEXbyKxAYncdHSTlpkY8xVI+b12j6eRRBZ9KWNyzc8B+O92I5neUBVKC1bNaZ1PW3Ze3p0uH3JS3KLJr6Zx1YcDwNjhL38LK9kcXtX47puAb/GsnZTceSUQn4QMPfE4IZTc7XIMSfEOXIoLXUj0EUoungbY584EOorZh6VWblH+PJLSHj1qtu9Uj7vSABKnRXtGyujdZXr9yiqd0rjX4GVoMxMaFSec2Y9dqdsQCMkpmk6czR+UOIpuX4QF7D3DojRqKVhnA2nns4esUiuFsg1TeONWQfquu1ga/R5b87YwHQOHVxKpeFiS13OitFS9qUtQlHSq89J6cYe7WLF8Q2O0dtWlEW01UnHwp/Uk2UNWlPLdjU9VeZSoO16joi3tw8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
