travis:
  secure:
    BINSTAR_TOKEN: qEKezvjhJryZCBGCE9kUQH59ovXhANW7BaSgv7BByFxwG214rhol7gPJHZypii7Iq+K7eKbQoTr4y/2VNvoWjqS2dUlKx51LEx1yPDZB/pRc9BfiK0+yVBLxcTD50k3ZB8tNLKCYHFV57xvM7PR1kt7moT4KmEMXlNA/rUgyKaIsxt6d70yz0THVMLLdFej/YWU/puJ2GiSKP9AIXAiZ3EPniYP7cLJu9xIyFFI33cCrpYGcWNOU9sCOr9AZieKY9GGsvxOldjqcGp3cxiCLBgqzVaiy6HgRSkcLUc0Bj0I+PeDksDYgGUBck+qU7UKDcDZl/ktA9G2koJIJY1NInFlkwGkvJylw6De4iRUbCe4oi+wOVGm+0UfF98lE6pTcczqcyJTkQ6QcgcypPiQ/bx4k8RXlCgiZQnfFll7Xe8UE+fN48RVDASgre1YJFQT9oZ5PJmVLr06lNTpqyPt1vP1kfCPSKg+j9DQ8tuWpBoZViiws+1KMkstMbJRW5vgsh6Z6EF92wRu8ziUnvvi24mw0T54CjrHQgsxOKT3Ua/B+xNEVT90OhDxK7R/pgJ1sT+XniOd9q3Y+s99UTM7ouXCCCP4SvXqkPFjVLiyUt4Bjvzl/Z1Rib49PvcvbMO7uwbKmkMmqLGIc6NQ2uuwDgUx+d5X8hgNpvUu/xA7SowQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
